#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yoshiaki Iwasawa
# SPDX-License-Identifier: BSD-3-Clause

import sys

for line in sys.stdin:
    input_line = line.strip() 

if input_line == "a":
    print("1")


